if: branch = master
language: node_js
node_js:
  - 12
cache: npm
script: npm run deploy
env:
  global:
    secure: Y1xIxvo6wDzy2F1lRU/AOZ56tiLHxM7hjN9z4nr+xEwpx007uOkrojSTYhDwfbqP46Qmhn6ZuC334tdVCmxNOTvWEoz+1hP1HV2EmATjOO0BowdnkLrdyAjsgLmOA+TB+woGLq/5kVeAwkbQO0rEJ9P/EFazNJp7OS09JisxINa4BTOXt+DT7JCafDGwVItpguRFxLKtELE221MAkw9VTpUVEzReD6/T63hT7A+NFmf7ALYXNzhKW3yNkGiWOHW2Lj8Fia/vqi6GOoCnJMW1F3zl+mI0rPohOMWSnN4tF+mCsQouLzzcs1PFEkd0yHp/nPC9CVAz9NNQR1g/HUXlNBmZV9fxTp+Nd5OGEgXZ+xno/hzSadbq4QzHs9Yt6FNNHLqri6DBd0Fk/bQw+2+hw1IONFVdcrMMhoN2qkcUP8Z8p2tWoyoF0KApeRD7i9f51WriOpyhq/dLf1ChDmDGT3oqk5HUR6+Nu5PG1WGUkdJKFZMoflKGPS7pieDCnx3QlCLTI5Tl4AqK7vr2vU9KMWuiGNSs7iXDLl+uE1/mESSWLhtZA8e0oxrfNS0eguL0Ps0+DINqvW1lFfT11pfH/+s67SzfU1sv0O8pazj1AJqNlHyJo3352P5wXCBnM3mHP5Bi9UgNmHgc7rpxbRUSFTiPjA74lkwmt3WgqNpSfDQ=
