if: branch = master
language: node_js
node_js:
  - 12
cache: npm
script: npm run deploy
env:
  global:
    secure: N5JQt4qpGk8F57tW1Ihpj9pZWCZXJa4TfcwIPChYnTxQVGLlJULqPuSYv4g6HlEz8eVreNIJMHtJOn1irxkZarGaZvTS3lS+7v/OenjHMbZseWh6R5mJlI2gQscORU3NXqnE4WVV/W7OMAjU1VQbVPmCxS3rLNe6RopCoqIQFGR7EHrf1xvqmUscArpuGFx/fSohOuJh6vuMR6HOhSqdmWoJdEDkXn/YXQE2KOFfD+4iTUsvPFXtSSqDTZw6QpfD+NA2wH7OtU6FOU2CTVB/wMK1IK0iTTsPNt+hz6jPUW/nQv9lqHXqEWg3wEEF+fBehzt32BSnc+Ue/G6b9HvBSUHLYU6zIGumi41V5EaphTygpT9sewL1Mv/EZ5TmGPYrXhdqKykexpHIqdAGCyLxZQv2+bMkYT914rlpbKE4k0PsHK12UGucb9pPzopYyabQTBQNQ8lzgrpWYCbTyjWHhuuhfPwk6UWT6P0YN0sdRUAQ2CuOFc9JuCvVLlluIlHan4sKGz7qlbV1rJ8ysEuxvuz9OYwH+MMlGH+Y8sGyTmAWe83A/EDrkcfl1q345imRlxTMo46I36dxfDNhCxFI2n58FYGmhS/IRAzo7y5HwGJJGhB4bDgIOyCzuTdjw3Fde0tcYj/NQunaVAGnQ5ADWldkB7yOIIBBWAiKjSGZl88=
