CREATE TABLE __WebKitDatabaseInfoTable__ (key TEXT NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT REPLACE,value TEXT NOT NULL ON CONFLICT FAIL);
INSERT INTO "__WebKitDatabaseInfoTable__" ( "key",value ) VALUES ( 'WebKitDatabaseVersionKey','1.0' );
CREATE TABLE arena(id integer PRIMARY KEY UNIQUE,day date,class varchar,wins integer);
INSERT INTO arena ( id,day,class,wins ) VALUES ( '1',NULL,'Mage','2' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '2',NULL,'Shaman','2' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '3',NULL,'Warlock','2' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '4','2013-12-08','Paladin','8' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '5','2013-12-09','Mage','6' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '6','2013-12-10','Paladin','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '7','2013-12-11','Mage','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '8','2013-12-12','Warlock','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '9',NULL,'Paladin','1' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '10',NULL,'Druid','1' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '11','2014-01-15','Mage','7' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '12','2014-01-15','Mage','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '13','2014-01-16','Druid','7' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '14','2014-01-17','Mage','8' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '15','2014-01-20','Priest','1' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '16','2014-01-21','Mage','6' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '17','2014-01-22','Druid','9' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '18','2014-01-22','Paladin','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '19','2014-01-23','Mage','7' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '20','2014-01-23','Mage','6' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '21','2014-01-24','Paladin','6' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '22','2014-01-24','Paladin','6' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '23','2014-01-25','Paladin','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '24','2014-01-25','Priest','2' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '25','2014-01-28','Paladin','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '26','2014-01-29','Druid','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '27','2014-01-31','Mage','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '28','2014-01-31','Paladin','6' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '29','2014-02-01','Shaman','1' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '30','2014-02-02','Rogue','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '31','2014-02-03','Rogue','6' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '32','2014-02-04','Mage','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '33','2014-02-05','Paladin','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '34','2014-02-06','Druid','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '35','2014-02-07','Druid','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '36','2014-02-07','Mage','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '37','2014-02-08','Mage','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '38','2014-02-09','Mage','12' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '39','2014-02-10','Mage','2' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '40','2014-02-10','Mage','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '41','2014-02-11','Rogue','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '42','2014-02-11','Druid','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '43','2014-02-11','Druid','1' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '44','2014-02-12','Druid','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '45','2014-02-12','Druid','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '46','2014-02-12','Druid','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '47','2014-02-14','Mage','8' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '48','2014-02-17','Druid','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '49','2014-02-18','Mage','7' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '50','2014-02-20','Mage','2' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '51','2014-02-21','Druid','8' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '52','2014-02-24','Druid','7' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '53','2014-02-24','Druid','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '54','2014-02-25','Paladin','10' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '55','2014-02-25','Druid','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '56','2014-02-26','Druid','9' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '57','2014-02-26','Rogue','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '58','2014-02-26','Druid','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '59','2014-02-27','Mage','12' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '60','2014-02-28','Mage','7' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '61','2014-02-28','Shaman','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '62','2014-02-28','Druid','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '63','2014-03-03','Druid','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '64','2014-03-03','Warlock','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '65','2014-03-04','Druid','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '66','2014-03-05','Druid','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '67','2014-03-06','Druid','2' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '68','2014-03-09','Shaman','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '69','2014-03-10','Shaman','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '70','2014-03-11','Rogue','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '71','2014-03-12','Mage','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '72','2014-03-13','Druid','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '73','2014-03-14','Mage','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '74','2014-03-15','Druid','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '75','2014-03-15','Mage','1' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '76','2014-03-18','Mage','11' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '77','2014-03-18','Rogue','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '78','2014-03-22','Paladin','8' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '79','2014-03-23','Rogue','2' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '80','2014-03-23','Druid','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '81','2014-03-24','Mage','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '82','2014-03-25','Mage','11' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '83','2014-03-26','Mage','9' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '84','2014-03-27','Mage','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '85','2014-03-28','Shaman','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '86','2014-03-30','Shaman','6' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '87','2014-03-31','Druid','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '88','2014-03-31','Mage','2' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '89','2014-04-02','Mage','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '90','2014-04-04','Mage','1' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '91','2014-04-05','Paladin','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '92','2014-04-06','Mage','10' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '93','2014-04-07','Druid','12' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '94','2014-04-16','Mage','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '95','2014-04-19','Druid','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '96','2014-04-19','Rogue','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '97','2014-05-10','Druid','9' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '98','2014-05-17','Paladin','7' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '99','2014-05-24','Mage','6' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '100','2014-05-31','Druid','3' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '101','2014-06-01','Paladin','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '102','2014-06-02','Mage','0' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '103','2014-06-03','Mage','12' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '104','2014-06-07','Paladin','8' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '105','2014-06-11','Rogue','6' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '106','2014-06-14','Mage','5' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '107','2014-06-14','Mage','7' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '108','2014-06-15','Druid','4' );
INSERT INTO arena ( id,day,class,wins ) VALUES ( '109','2014-06-15','Druid','9' );
CREATE TABLE lacks(id integer PRIMARY KEY AUTOINCREMENT UNIQUE,card_id integer,card_name text,card_quality integer);
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '9','50003','Archmage Antonidas','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '10','50035','Tirion Fordring','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '12','30042','Keeper of the Grove','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '13','30048','Lightwell','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '14','30052','Mass Dispel','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '17','30054','Master of Disguise','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '18','30054','Master of Disguise','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '21','30007','Angry Chicken','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '22','30058','Murloc Tidecaller','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '23','30058','Murloc Tidecaller','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '24','30081','Young Priestess','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '25','30006','Ancient Watcher','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '26','30080','Wild Pyromancer','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '27','30002','Alarm-o-Bot','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '29','30018','Coldlight Oracle','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '30','30041','Injured Blademaster','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '31','30074','Sunwalker','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '32','30063','Ravenholdt Assassin','2' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '33','40001','Ancient of Lore','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '34','40005','Bestial Wrath','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '35','40034','Snake Trap','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '36','40017','Gladiator''s Longbow','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '37','40017','Gladiator''s Longbow','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '38','40020','Ice Block','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '39','40036','Spellbender','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '40','40037','Sword of Justice','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '41','40032','Shadowform','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '42','40009','Cabal Shadow Priest','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '43','40009','Cabal Shadow Priest','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '44','40029','Preparation','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '45','40029','Preparation','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '46','40027','Patient Assassin','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '48','40021','Kidnapper','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '50','40011','Doomhammer','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '51','40011','Doomhammer','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '52','40028','Pit Lord','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '53','40028','Pit Lord','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '54','40038','Twisting Nether','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '55','40038','Twisting Nether','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '56','40004','Bane of Doom','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '58','40033','Shield Slam','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '59','40008','Brawl','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '60','40008','Brawl','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '61','40019','Hungry Crab','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '62','40012','Doomsayer','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '63','40012','Doomsayer','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '64','40007','Blood Knight','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '65','40035','Southsea Captain','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '66','40014','Faceless Manipulator','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '67','40014','Faceless Manipulator','1' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '69','50029','Prophet Velen','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '70','50010','Edwin VanCleef','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '71','50001','Al''Akir the Windlord','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '72','50013','Grommash Hellscream','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '73','50005','Bloodmage Thalnos','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '74','50024','Millhouse Manastorm','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '75','50025','Nat Pagle','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '76','50019','King Mukla','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '77','50034','Tinkmaster Overspark','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '78','50007','Captain Greenskin','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '79','50011','Elite Tauren Chieftain','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '80','50006','Cairne Bloodhoof','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '81','50012','Gelbin Mekkatorque','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '82','50016','Hogger','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '83','50017','Illidan Stormrage','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '85','50032','The Beast','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '86','50014','Gruul','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '87','50002','Alexstrasza','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '88','50023','Malygos','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '89','50028','Onyxia','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '90','50036','Ysera','0' );
INSERT INTO lacks ( id,"card_id","card_name","card_quality" ) VALUES ( '91','50031','Sylvanas Windrunner','0' );
CREATE TABLE packs(id integer PRIMARY KEY UNIQUE,day date,count_gl integer,count_ge integer,count_gr integer,count_gc integer,count_l integer,count_e integer,count_r integer,count_c integer,tip_gl text,tip_ge text,tip_gr text,tip_gc text,tip_l text,tip_e text,tip_r text,tip_c text,dust integer);
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '1','2014-03-03','0','0','1','0','0','0','2','2',NULL,NULL,'Ethereal Arcanist',NULL,NULL,NULL,'?',NULL,'150' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '2','2014-03-03','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'?',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '3','2014-03-04','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Crazed Alchemist',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '4','2014-03-05','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Equality',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '5','2014-03-06','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Headcrack',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '6','2014-03-09','0','0','0','0','0','1','2','2',NULL,NULL,NULL,NULL,NULL,'Lay on Hands','Crazed Alchemist
Explosive Shot',NULL,'150' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '7','2014-03-10','0','0','0','0','0','1','0','4',NULL,NULL,NULL,NULL,NULL,'Gorehowl',NULL,NULL,'120' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '8','2014-03-11','0','0','0','1','0','1','1','2',NULL,NULL,NULL,'Tauren Warrior',NULL,'Mountain Giant','Demolisher',NULL,'180' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '9','2014-03-12','0','0','0','0','1','1','0','3',NULL,NULL,NULL,NULL,'Nozdormu','Ancient of War',NULL,NULL,'515' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '10','2014-03-13','1','0','0','0','0','0','0','4','King Krush',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1620' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '11','2014-03-14','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Mana Wraith',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '12','2014-03-15','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Savagery',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '13','2014-03-15','0','0','0','1','0','1','0','3',NULL,NULL,NULL,'Sense Demons',NULL,'Ice Block',NULL,NULL,'165' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '14','2014-03-18','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Injured Blademaster',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '15','2014-03-18','0','0','0','0','0','1','1','3',NULL,NULL,NULL,NULL,NULL,'Earth Elemental','Violet Teacher',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '16','2014-03-18','0','0','0','0','0','1','2','2',NULL,NULL,NULL,NULL,NULL,'Avenging Wrath','Savagery
Mana Tide Totem',NULL,'150' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '17','2014-03-18','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'SI:7 Agent',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '18','2014-03-18','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Equality',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '19','2014-03-19','0','0','0','0','0','1','1','3',NULL,NULL,NULL,NULL,NULL,'Mindgames','Gadgetzan Auctioneer',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '20','2014-03-22','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Bloodsail Corsair',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '21','2014-03-23','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Imp Master',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '22','2014-03-23','0','0','0','1','1','1','1','1',NULL,NULL,NULL,'Ironbeak Owl','Harrison Jones','Southsea Captain','Knife Juggler',NULL,'575' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '23','2014-03-23','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Lightning Storm',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '24','2014-03-24','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Siphon Soul',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '25','2014-03-25','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Equality',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '26','2014-03-26','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Master Swordsmith',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '27','2014-03-26','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Void Terror',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '28','2014-03-26','0','0','1','0','0','0','1','3',NULL,NULL,'Auchenai Soulpriest',NULL,NULL,NULL,'Holy Wrath',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '29','2014-03-26','0','0','0','0','0','0','2','3',NULL,NULL,NULL,NULL,NULL,NULL,'Holy Wrath
Misdirection',NULL,'55' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '30','2014-03-26','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Explosive Shot',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '31','2014-03-26','0','0','0','0','0','1','1','3',NULL,NULL,NULL,NULL,NULL,'Earth Elemental','Perdition''s Blade',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '32','2014-03-26','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Arcane Golem',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '33','2014-03-27','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Master Swordsmith',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '34','2014-03-28','0','1','0','0','0','0','0','4',NULL,'Gorehowl',NULL,NULL,NULL,NULL,NULL,NULL,'420' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '35','2014-03-30','0','0','1','0','0','0','1','3',NULL,NULL,'Vaporize',NULL,NULL,NULL,'Lava Burst',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '36','2014-03-31','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Equality',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '37','2014-03-31','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Starfall',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '38','2014-03-31','0','0','0','0','0','1','0','4',NULL,NULL,NULL,NULL,NULL,'Bane of Doom',NULL,NULL,'120' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '39','2014-04-02','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Ravenholdt Assassin',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '40','2014-04-04','0','0','0','0','0','1','2','2',NULL,NULL,NULL,NULL,NULL,'Avenging Wrath','Imp Master
Wild Pyromancer',NULL,'150' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '41','2014-04-05','0','0','0','1','0','0','1','3',NULL,NULL,NULL,'Silence',NULL,NULL,'Lava Burst',NULL,'85' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '42','2014-04-06','0','0','1','0','0','0','2','2',NULL,NULL,'Auchenai Soulpriest',NULL,NULL,NULL,'Misdirection
Sunfury Protector',NULL,'150' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '43','2014-04-07','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Pint-Sized Summoner',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '44','2014-04-07','0','0','0','0','1','0','0','4',NULL,NULL,NULL,NULL,'Lorewalker Cho',NULL,NULL,NULL,'420' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '45','2014-04-07','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Sunwalker',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '46','2014-04-07','0','0','0','0','1','0','1','3',NULL,NULL,NULL,NULL,'The Black Knight',NULL,'Doomguard',NULL,'435' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '47','2014-04-07','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Blessed Champion',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '48','2014-04-13','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Mortal Strike',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '49','2014-04-13','0','0','0','0','0','1','1','3',NULL,NULL,NULL,NULL,NULL,'Force of Nature','Defender of Argus',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '50','2014-04-13','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Felguard',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '51','2014-04-13','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Crazed Alchemist',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '52','2014-04-13','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Equality',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '53','2014-04-16','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Holy Wrath',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '54','2014-04-17','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Kirin Tor Mage',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '55','2014-04-19','0','0','0','0','0','0','2','3',NULL,NULL,NULL,NULL,NULL,NULL,'Arcane Golem
Ancient Mage',NULL,'55' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '56','2014-04-19','0','0','1','0','0','1','0','3',NULL,NULL,'Knife Juggler',NULL,NULL,'Hungry Crab',NULL,NULL,'215' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '57','2014-05-09','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Emperor Cobra',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '58','2014-05-09','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Shadowflame',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '59','2014-05-10','0','0','0','1','0','0','1','3',NULL,NULL,NULL,'Dread Corsair',NULL,NULL,'Knife Juggler',NULL,'85' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '60','2014-05-17','0','0','0','0','0','1','2','2',NULL,NULL,NULL,NULL,NULL,'Spellbender','Azure Drake
Demolisher',NULL,'150' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '61','2014-05-24','0','0','0','0','0','1','1','3',NULL,NULL,NULL,NULL,NULL,'Big Game Hunter','Imp Master',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '62','2014-05-31','0','0','0','0','0','0','2','3',NULL,NULL,NULL,NULL,NULL,NULL,'Alarm-o-Bot
Ancient Mage',NULL,'55' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '63','2014-06-01','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Mana Tide Totem',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '64','2014-06-02','0','0','1','0','0','0','1','3',NULL,NULL,'Eaglehorn Bow',NULL,NULL,NULL,'Master Swordsmith',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '65','2014-06-03','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Vaporize',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '66','2014-06-03','0','0','0','0','0','0','2','3',NULL,NULL,NULL,NULL,NULL,NULL,'Counterspell
Arcane Golem',NULL,'55' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '67','2014-06-07','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Shadow Madness',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '68','2014-06-11','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Coldlight Oracle',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '69','2014-06-14','0','0','0','0','0','1','1','3',NULL,NULL,NULL,NULL,NULL,'Ancient of War','Arcane Golem',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '70','2014-06-14','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Perdition''s Blade',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '71','2014-06-15','0','0','0','0','0','1','0','4',NULL,NULL,NULL,NULL,NULL,'Far Sight',NULL,NULL,'120' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '72','2014-06-15','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Frothing Berserker',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '73','2014-06-18','0','0','0','0','0','1','1','3',NULL,NULL,NULL,NULL,NULL,'Kidnapper','Armorsmith',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '74','2014-06-18','0','0','0','0','0','1','1','3',NULL,NULL,NULL,NULL,NULL,'Shield Slam','Felguard',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '75','2014-06-18','0','0','1','0','0','0','1','3',NULL,NULL,'Auchenai Soulpriest',NULL,NULL,NULL,'Commanding Shout',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '76','2014-06-18','0','0','0','0','0','0','2','3',NULL,NULL,NULL,NULL,NULL,NULL,'Emperor Cobra
Bloodsail Corsair',NULL,'55' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '77','2014-06-18','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Doomguard',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '78','2014-06-18','0','0','0','0','0','1','1','3',NULL,NULL,NULL,NULL,NULL,'Gorehowl','Ethereal Arcanist',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '79','2014-06-18','0','0','0','1','1','0','0','3',NULL,NULL,NULL,'Flame Imp','Lord Jaraxxus',NULL,NULL,NULL,'465' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '80','2014-06-18','0','0','0','0','0','0','1','4',NULL,NULL,NULL,NULL,NULL,NULL,'Eaglehorn Bow',NULL,'40' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '81','2014-06-18','0','0','0','0','0','1','1','3',NULL,NULL,NULL,NULL,NULL,'Sea Giant','Shadowflame',NULL,'135' );
INSERT INTO packs ( id,day,"count_gl","count_ge","count_gr","count_gc","count_l","count_e","count_r","count_c","tip_gl","tip_ge","tip_gr","tip_gc","tip_l","tip_e","tip_r","tip_c",dust ) VALUES ( '82','2014-06-18','0','0','0','0','0','0','2','3',NULL,NULL,NULL,NULL,NULL,NULL,'SI:7 Agent
Knife Juggler',NULL,'55' );
